"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const ControladorReserva_1 = require("../control/ControladorReserva");
const ControladorReservaHuesped_1 = require("../control/ControladorReservaHuesped");
const router = (0, express_1.Router)();
const controladorReserva = new ControladorReserva_1.ControladorReserva();
const controladorHuespedes = new ControladorReservaHuesped_1.ControladorReservaHuesped();
router.get('/activas', (req, res) => controladorReserva.listarActivas(req, res));
router.post('/', (req, res) => controladorReserva.crear(req, res));
router.get('/:id', (req, res) => controladorReserva.buscarPorId(req, res));
router.put('/:id/cancelar', (req, res) => controladorReserva.cancelar(req, res));
router.get('/:idReserva/huespedes', (req, res) => controladorHuespedes.listarPorReserva(req, res));
router.post('/:idReserva/huespedes', (req, res) => controladorHuespedes.agregarHuesped(req, res));
router.delete('/:idReserva/huespedes/:idHuesped', (req, res) => controladorHuespedes.quitarHuesped(req, res));
router.put('/:idReserva/huespedes/titular', (req, res) => controladorHuespedes.cambiarTitular(req, res));
exports.default = router;
