"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const ControladorTipoHabitacion_1 = require("../control/ControladorTipoHabitacion");
const router = (0, express_1.Router)();
const controlador = new ControladorTipoHabitacion_1.ControladorTipoHabitacion();
router.get('/:id', (req, res) => controlador.buscarPorId(req, res));
router.get('/', (req, res) => controlador.listar(req, res));
router.post('/', (req, res) => controlador.crear(req, res));
router.put('/:id', (req, res) => controlador.actualizar(req, res));
exports.default = router;
