"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const ControladorUsuario_1 = require("../control/ControladorUsuario");
const router = (0, express_1.Router)();
const controlador = new ControladorUsuario_1.ControladorUsuario();
router.post('/autenticar', (req, res) => controlador.autenticar(req, res));
router.post('/', (req, res) => controlador.crear(req, res));
router.get('/:id', (req, res) => controlador.buscarPorId(req, res));
router.delete('/:id', (req, res) => controlador.desactivar(req, res));
exports.default = router;
