"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const ControladorHabitacion_1 = require("../control/ControladorHabitacion");
const router = (0, express_1.Router)();
const controlador = new ControladorHabitacion_1.ControladorHabitacion();
router.get('/disponibles', (req, res) => controlador.listarDisponibles(req, res));
router.get('/piso/:piso', (req, res) => controlador.listarPorPiso(req, res));
router.get('/:id', (req, res) => controlador.buscarPorId(req, res));
router.get('/', (req, res) => controlador.listar(req, res));
router.put('/:id/estado', (req, res) => controlador.cambiarEstado(req, res));
exports.default = router;
